# .github/workflows/deploy.yml

name: Deploy Docker on local Windows Runner

on:
  push:
    branches:
      - main                                # триггер на пуши в main

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]       # ваш self-hosted Windows runner

    # передаём секрет в переменную окружения всего job
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout code via git clone
        # GITHUB_TOKEN создаётся автоматически перед стартом job :contentReference[oaicite:0]{index=0}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          # клонируем только нужную ветку и один коммит
          git clone --depth 1 \
            --branch "$BRANCH" \
            "https://x-access-token:$TOKEN@github.com/$REPO.git" .

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .

      - name: Stop previous container
        run: |
          docker rm -f my-app || exit 0

      - name: Run new container with Telegram token
        run: |
          docker run -d --name my-app \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            my-app:${{ github.sha }}
