# .github/workflows/deploy.yml

name: Deploy Docker on local Windows Runner

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: [self-hosted, windows]
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}       # Telegram bot token stored in GitHub Secrets
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token for repo checkout

    steps:
      - name: Clone into fresh folder
        shell: powershell
        run: |
          # Extract branch name (refs/heads/main -> main)
          $branch = $env:GITHUB_REF -replace '^refs/heads/',''
          Write-Host "==> Cloning branch: $branch"

          # Set repository and derive image/container name
          $repoFull  = $env:GITHUB_REPOSITORY            # owner/repo
          $repoName  = $repoFull.Split('/')[1]           # repo
          Write-Host "==> Repository name: $repoName"

          # Build clone URL with GITHUB_TOKEN
          $url  = "https://x-access-token:$($env:GITHUB_TOKEN)@github.com/$repoFull.git"
          Write-Host "==> Clone URL masked: $($url.Substring(0,40))..."

          # Remove existing clone folder if it exists
          $path = Join-Path $PWD "fresh_repo"
          if (Test-Path $path) {
            Write-Host "==> Removing existing 'fresh_repo' directory"
            Remove-Item -Recurse -Force $path
          }

          # Create and enter clean directory
          New-Item -ItemType Directory -Path $path | Out-Null
          Set-Location $path

          # Clone only latest commit from target branch
          git clone --depth 1 --branch $branch $url .
          if ($LASTEXITCODE -ne 0) {
            Write-Error "❌ git clone failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }

      - name: Build Docker image
        shell: powershell
        run: |
          # Build (or rebuild) Docker image with tag 'repoName:latest'
          Write-Host "==> Building Docker image: $repoName:latest"
          docker build -t $repoName:latest fresh_repo

      - name: Stop and remove existing container
        shell: powershell
        run: |
          # Stop and remove old container named 'repoName'
          Write-Host "==> Removing existing container: $repoName (if any)"
          try {
            docker rm -f $repoName
          } catch {
            Write-Host "No existing container to remove."
          }

      - name: Run container and verify startup
        shell: powershell
        run: |
          # Run container in detached mode and capture its ID
          Write-Host "==> Starting container: $repoName"
          $cid = docker run -d --name $repoName `
            -e BOT_TOKEN="$env:BOT_TOKEN" `
            $repoName:latest
          Write-Host "✅ Container started with ID: $cid"

          # Verify the container is running
          $running = docker ps -q --filter "id=$cid"
          if ($running -eq $cid) {
            Write-Host "✅ Verification passed: container is running"
          } else {
            Write-Error "❌ Verification failed: container is NOT running"
            exit 1
          }
